import { transformMoexResponse } from "./transformMoexResponse.ts";
import response from "./mockSecurityMoexResponse.json";
import { expect, test } from 'vitest';

test("Группирует названия колонок и даные", () => {
  const actualResult = transformMoexResponse(response.securities);
  expect(actualResult[0]).toEqual({
    "SECID": "SU25085RMFS0",
    "BOARDID": "TQOB",
    "SHORTNAME": "ОФЗ 25085",
    "PREVWAPRICE": null,
    "YIELDATPREVWAPRICE": 0,
    "COUPONVALUE": 31.91,
    "NEXTCOUPON": "2025-03-26",
    "ACCRUEDINT": 24.55,
    "PREVPRICE": null,
    "LOTSIZE": 1,
    "FACEVALUE": 1000,
    "BOARDNAME": "Т+: Гособлигации - безадрес.",
    "STATUS": "A",
    "MATDATE": "2025-09-24",
    "DECIMALS": 4,
    "COUPONPERIOD": 182,
    "ISSUESIZE": 15000000,
    "PREVLEGALCLOSEPRICE": null,
    "PREVDATE": "2025-02-10",
    "SECNAME": "ОФЗ-ПД 25085 24/09/2025",
    "REMARKS": null,
    "MARKETCODE": "FNDT",
    "INSTRID": "GOFZ",
    "SECTORID": null,
    "MINSTEP": 0.001,
    "FACEUNIT": "SUR",
    "BUYBACKPRICE": 100,
    "BUYBACKDATE": "0000-00-00",
    "ISIN": "RU000A103BQ2",
    "LATNAME": "OFZ-PD 25085",
    "REGNUMBER": "25085RMFS",
    "CURRENCYID": "SUR",
    "ISSUESIZEPLACED": 15000000,
    "LISTLEVEL": 1,
    "SECTYPE": "3",
    "COUPONPERCENT": 6.4,
    "OFFERDATE": null,
    "SETTLEDATE": "2025-02-12",
    "LOTVALUE": 1000,
    "FACEVALUEONSETTLEDATE": 1000,
    "CALLOPTIONDATE": null,
    "PUTOPTIONDATE": null,
    "DATEYIELDFROMISSUER": null
})
  expect(actualResult[56]).toEqual({
    "SECID": "SU52005RMFS4",
    "BOARDID": "TQOB",
    "SHORTNAME": "ОФЗ 52005",
    "PREVWAPRICE": 66.703,
    "YIELDATPREVWAPRICE": 8.28,
    "COUPONVALUE": 14.54,
    "NEXTCOUPON": "2025-05-21",
    "ACCRUEDINT": 6.65,
    "PREVPRICE": 66.5,
    "LOTSIZE": 1,
    "FACEVALUE": 1155.55,
    "BOARDNAME": "Т+: Гособлигации - безадрес.",
    "STATUS": "A",
    "MATDATE": "2033-05-11",
    "DECIMALS": 4,
    "COUPONPERIOD": 182,
    "ISSUESIZE": 350000000,
    "PREVLEGALCLOSEPRICE": 66.499,
    "PREVDATE": "2025-02-10",
    "SECNAME": "ОФЗ-ИН 52005 11/05/33",
    "REMARKS": null,
    "MARKETCODE": "FNDT",
    "INSTRID": "GOFZ",
    "SECTORID": null,
    "MINSTEP": 0.001,
    "FACEUNIT": "SUR",
    "BUYBACKPRICE": 100,
    "BUYBACKDATE": "0000-00-00",
    "ISIN": "RU000A105XV1",
    "LATNAME": "OFZ-IN 52005",
    "REGNUMBER": "52005RMFS",
    "CURRENCYID": "SUR",
    "ISSUESIZEPLACED": 220696983,
    "LISTLEVEL": 1,
    "SECTYPE": "3",
    "COUPONPERCENT": 2.5,
    "OFFERDATE": null,
    "SETTLEDATE": "2025-02-12",
    "LOTVALUE": 1155.55,
    "FACEVALUEONSETTLEDATE": 1156.13,
    "CALLOPTIONDATE": null,
    "PUTOPTIONDATE": null,
    "DATEYIELDFROMISSUER": null
})
  expect(actualResult).toHaveLength(57)
})
// из джейсона берём объект response.securities (в нем поля columns и data)
// и функция превращает его в массив объектов
// написать функцию и тесты к ней
// вызывать её в downloadOFZ